//AUTH ACTIONS
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_FINISH= 'AUTH_FINISH';
export const AUTH_ERROR_CLEAN= 'AUTH_ERROR_CLEAN';
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SHOW_PASSWORD = "SHOW_PASSWORD";

//NAVIGATION ACTIONS
export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';

//ANIMATION ACTIONS
export const ANIMATE_START = 'ANIMATE_START';
export const ANIMATE_STOP = 'ANIMATE_STOP';